myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"
urlpatterns = [
    path('trail/',views.trail,name='trail'),
    path('profile/',views.profile,name='profile'),
    path('get_demo/',views.get_demo,name="get_demo"),
    path('post_demo/',views.post_demo,name="post_demo"),
    path('register/',views.register,name="register"),
    path('multi/',views.multi,name="multiselect"),
    path('img_upld/',views.img_upld,name="img_upld"),
    path('img_display/',views.img_display,name="img_display"),
    path('builtin/',views.builtin,name='builtin'),
]

p21/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import myapp
from myapp import views
urlpatterns = [
   path('admin/', admin.site.urls),
    path('base/',views.base,name="base"),
    path('',views.home,name="home"),
    path('myapp/',include("myapp.urls")),
    
]
if settings.DEBUG==True:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

myapp/models.py
from django.db import models

# Create your models here.

myapp/forms.py
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
import re

def validate_name(Name):
    m=re.match('[a-zA-Z]+',Name)
    if m.group()!=Name:
        raise ValidationError("Name is Not valid")
    return Name

class SampleForm(forms.Form):
    Name=forms.CharField(max_length=200,required=True,label="Name :",
    validators=[validate_name])
    
    Email=forms.EmailField(max_length=100,required=True,label="Email :",
    validators=[validators.MinLengthValidator(10)])

    ConfirmEmail=forms.EmailField(max_length=100,required=True,label="Confirm Email :")
    IPaddress=forms.CharField(max_length=100,required=True,label="IP address :",
    validators=[validators.validate_ipv4_address])
    Password=forms.CharField(max_length=200,required=True,label="Password :",widget=forms.PasswordInput(attrs={'placeholder':"Password"}))
    Profile_Pic=forms.ImageField(max_length=200,required=False,label="Profile Pic :")
    botcacher=forms.CharField(max_length=10,required=False,widget=forms.HiddenInput)
    def clean(self,*args,**kwargs):
        cleaned_data=super().clean()
        email=cleaned_data.get("Email")
        cemail=cleaned_data.get("ConfirmEmail")
        if email==cemail:
            return cleaned_data
        self.add_error('ConfirmEmail',"Both the emails are not same")
    def clean_name(self):
	    Name=self.cleaned_data.get("Name")
	    for i in Name:
		    if not('a'<=i<='z' or 'A'<=i<='Z'):
			    raise ValidationError("Name must contain only alphabets")
	    return Name    
    def clean_botcacher(self):
        data=self.cleaned_data.get("botcacher")
        if len(data)==0:
            return data
        self.add_error("Name","Hey CHITTI I Got You")

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.core.mail import send_mail
from django.core.files.storage import FileSystemStorage
from myapp.utilities import store_Image
from myapp import utilities
def trail(request):
    return HttpResponse("<h1>Project is on Air</h1>")
def base(request):
    return render(request,"base.html")
def home(request):
    return render(request,"myapp/home.html")
def profile(request):
    name="Akhil"
    return render(request,"myapp/profile.html",{'name':name})
def get_demo(request):
    name=request.GET.get('name')
    return render(request,"get_demo.html",{'name':name})
def post_demo(request):
    if request.method=="POST": 
        name=request.POST.get('name')
        return HttpResponse("<h1>Thanks for submission MR./MS. {}</h1>".format(name))
    return render(request,"post_demo.html")
def register(request):
    if request.method=="POST":
        First_Name=request.POST.get("First_Name")
        Last_Name=request.POST.get("Last_Name")
        Email=request.POST.get("Email")
        Phone_Number=request.POST.get("Phone_Number")
        Password=request.POST.get("Password")
        date=request.POST.get("birthday_day")
        month=request.POST.get("birthday_month")
        year=request.POST.get("birthday_year")
        gender=request.POST.get("sex")
        if gender=="1":
            gender="FeMale"
        else:
            gender="Male"

        send_mail("Thanks For Registration","hello Mr./Ms.{} {}\n Thanks for Registering".format(First_Name,Last_Name),
        "m.akhilchowdary97@gmail.com",[Email,],fail_silently=True)
        return redirect("home")
    return render(request,"myapp/registration.html")
def multi(request):
    if request.method=="POST":
        foods=request.POST.getlist("food")
        languages=request.POST.getlist("language")
        return HttpResponse("<h1>{}{}<h1>".format(foods,languages))
    return render(request,"multiselect.html")
def img_upld(request):
    return render(request,"img_upld.html")
def img_display(request):
    file_url=False
    if request.method=="POST" and request.FILES:
        Image1=request.FILES.get('Akh')
        Image2=request.FILES.get('Akhi')
        Image3=request.FILES.get('Akhil')
        file_urls=map(store_Image,[Image1,Image2,Image3])
    return render(request,"img_display.html",context={'file_urls':file_urls})

from myapp import forms
def builtin(request):
    if request.method=="POST":
        form=forms.SampleForm(request.POST,request.FILES)
        if form.is_valid()==False:
            return render(request,"builtin.html",{'form':form})
        else:
            data=form.cleaned_data
            Profile_Pic=data['Profile_Pic']
            utilities.store_Image(Profile_Pic)
            print(form.cleaned_data)
    form=forms.SampleForm()
    return render(request,"builtin.html",{'form':form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
       <title> Base HTML File</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</head>
<body>
    {% include "partials/_topbar.html" %}
    {% include "partials/_navbar.html" %} 
     {% block content %}
       <div class="container">
         <div class="jumbotron">
             <h1>Welcome to Base Page</h1>
             <img src="{% static 'images/c.jpg' %}" alt="No Image Found" height="500" width="1000">
         </div>
       </div>
     {% endblock %}
     {% include "partials/_footer.html" %}    
</body>
</html>

templates/builtin.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Built In Forms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
    <form  method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    <!--{{form.as_p}}-->
    <table border="2pt">
        <div class="row">
            <div class="col-2">
                {{form.Name|as_crispy_field}}
            </div>
            <div class="col-2">
                {{form.IPaddress|as_crispy_field}}
            </div>
        </div>
        <div class="row">
            <div class="col-2">
                {{form.Email|as_crispy_field}}
            </div>
            <div class="col-2">
                {{form.ConfirmEmail|as_crispy_field}}
            </div>
        </div>
        <div class="row">
            <div class="col-2">
                {{form.Password|as_crispy_field}}
            </div>
            <div class="col-2">
                {{form.Profile_Pic|as_crispy_field}}
            </div>
        </div>
    
        
    </table>
    <!-- <ul>
        {{ form.as_ul }}
    </ul>-->
    {{form.botcacher}}
    <input type="submit" value="submit">
</form>
</body>
</html>

templates/display_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Display</title>
</head>
<body>
    <h1>{{Name}}</h1>
    <h1>{{Email}}</h1>
    <h1>{{ConfirmEmail}}</h1>
    <h1>{{IPaddress}}</h1>
    <h1>{{Password}}</h1>
    <h1>{{Profile_Pic}}</h1>
    
    

</body>
</html>

templates/get_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=g, initial-scale=1.0">
    <title>Get Page</title>
</head>
<body>
    <form method ="GET">
        <label for="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="submit">
    </form>
    <h1>{{name}}</h1>

</body>
</html>

templates/img_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>uploaded images</title>
</head>
<body>
    {% for file_url in file_urls %}
    {% if file_url %}
    <img src="{{file_url}}" alt="No Image Found" height="300" width="300">
    {% endif %}
    {% endfor %}
   

</body>
</html>

templates/img_upld.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IMAGE UPLOAD</title>
</head>
<body>
    <form action="{% url 'myapp:img_display' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        Image1:<input type="file" name="Akh" id="Akh"><br>
        Image2:<input type="file" name="Akhi" id="Akhi"><br>
        Image3:<input type="file" name="Akhil" id="Akhil"><br>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/multiselect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MultiSelect and Checkboxes</title>
</head>
<body>
    <form method="POST" class="form-group">
        {% csrf_token %}
        <lable for="langauges">CHOOSE YOUR LANGUAGE:</lable>
         <select name="language" id = "languages" multiple>
             <option value="Python">Python</option>
             <option value="Java">Java</option>
             <option value="C#">C#</option>
             <option value="C++">C++</option>
             <option value="C">C</option>
         </select><br>
         <h4>CHOOSE YOUR FOOD</h4>
         <label for="Idli">
             Idli
         </label>
         <input type="checkbox" name="food" id="idli" value="IDLI">
         <label for="Vada">
            Vada
        </label>
        <input type="checkbox" name="food" id="vada" value="VADA">
        <label for="Dosa">
            Dosa
        </label>
        <input type="checkbox" name="food" id="dosa" value="DOSA">
        <label for="Puri">
           Puri
        </label>
        <input type="checkbox" name="food" id="puri" value="PURI"><br>
        <br><input type="submit" value="submit" class="btn btn-primary">
</body>
</html>

templates/myapp/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title> Home Page </title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to Home Page</h1>
            <img src="{% static 'images/d.jpg' %}" alt="No Image Found" height="500" width="1000">
        </div>
      </div>
{% endblock %}

templates/myapp/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title> Profile Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to {{name}} Profile Page</h1>
            <img src="{% static 'images/ak.jpg' %}" alt="No Image Found" height="500" width="1000">
        </div>
      </div>
{% endblock %}

templates/partials/_footer.html
<div class="alert alert-info" role="alert">
    <center>Footer</center> 
  </div>
  

templates/partials/_navbar.html
<div class="container">
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:profile' %}">Profile</a>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:register' %}">Registration</a>
        </li>
        
      </ul>
</div>

templates/partials/_topbar.html
<div class="alert alert-danger" role="alert">
    <center>Top Bar</center> 
</div>

templates/post_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=g, initial-scale=1.0">
    <title>Post Page</title>
</head>
<body>
    <form method ="POST">
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="submit">
    </form>
    

</body>
</html>